/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controllers

import (
	"_case_api/src/models"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
)

// GetCFItem - The REST read request message for the getCFItem() API call.
func GetCFItem(c *gin.Context) {
	var item = models.CfItemType{
		Identifier:           "",
		FullStatement:        "",
		AlternativeLabel:     "",
		CFItemType:           "",
		Uri:                  "",
		HumanCodingScheme:    "",
		ListEnumeration:      "",
		AbbreviatedStatement: "",
		ConceptKeywords:      nil,
		ConceptKeywordsURI:   models.LinkUriType{},
		Notes:                "",
		Language:             "",
		EducationLevel:       nil,
		CFItemTypeURI:        models.LinkUriType{},
		LicenseURI:           models.LinkUriType{},
		StatusStartDate:      "",
		StatusEndDate:        "",
		LastChangeDateTime:   time.Time{},
		CFDocumentURI:        models.LinkUriType{},
	}
	c.JSON(http.StatusOK, item)
}
