/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controllers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCFRubric - The REST read request message for the getCFRubric() API call.
func GetCFRubric(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
