/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
)

// GetAllCFDocuments - The REST read request message for the getAllCFDocuments() API call.
func GetAllCFDocuments(c *gin.Context) {
	var d = CfDocumentTypeAllOf{
		CFPackageURI: LinkUriType{},
	}
	c.JSON(http.StatusOK, d)
}

// GetCFDocument - The REST read request message for the getCFDocument() API call.
func GetCFDocument(c *gin.Context) {
	var d = CfDocumentType{
		Identifier:         "",
		Uri:                "",
		Creator:            "",
		Title:              "",
		LastChangeDateTime: time.Time{},
		OfficialSourceURL:  "",
		Publisher:          "",
		Description:        "",
		Subject:            nil,
		SubjectURI:         nil,
		Language:           "",
		Version:            "",
		AdoptionStatus:     "",
		StatusStartDate:    "",
		StatusEndDate:      "",
		LicenseURI:         LinkUriType{},
		Notes:              "",
		CFPackageURI:       LinkUriType{},
	}
	c.JSON(http.StatusOK, d)
}
