/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCFAssociationGrouping - The REST read request message for the getCFAssociationGrouping() API call.
func GetCFAssociationGrouping(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCFConcept - The REST read request message for the getCFConcept() API call.
func GetCFConcept(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCFItemType - The REST read request message for the getCFItemType() API call.
func GetCFItemType(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCFLicense - The REST read request message for the getCFLicense() API call.
func GetCFLicense(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCFSubject - The REST read request message for the getCFSubject() API call.
func GetCFSubject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
