/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCFAssociation - The REST read request message for the getCFAssociation() API call.
func GetCFAssociation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCFItemAssociations - The REST read request message for the getCFItemAssociations() API call.
func GetCFItemAssociations(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
