/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CfPackageType - This is the container for all of the data for a Competency Framework Package i.e. the root CFDocument and ALL of the corresponding components i.e. the CFItems, CFAssociations and CFDefinitions. 
type CfPackageType struct {

	CFDocument CfPckgDocumentType `json:"CFDocument"`

	CFItems []CfPckgItemType `json:"CFItems,omitempty"`

	CFAssociations []CfPckgAssociationType `json:"CFAssociations,omitempty"`

	CFDefinitions CfDefinitionType `json:"CFDefinitions,omitempty"`

	CFRubrics []CfRubricType `json:"CFRubrics,omitempty"`
}
