/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

// CfAssociationType - This is the container for the data about the relationship between two CFDocuments or between two CFItems outside of the context of a CFPackage or CFItem.
type CfAssociationType struct {

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	Identifier string `json:"identifier"`

	AssociationType string `json:"associationType"`

	// Model Primitive Datatype = Integer
	SequenceNumber int32 `json:"sequenceNumber,omitempty"`

	// Model Primitive Datatype = AnyURI
	Uri string `json:"uri"`

	OriginNodeURI LinkGenUriType `json:"originNodeURI"`

	DestinationNodeURI LinkGenUriType `json:"destinationNodeURI"`

	CFAssociationGroupingURI LinkUriType `json:"CFAssociationGroupingURI,omitempty"`

	// Model Primitive Datatype = DateTime
	LastChangeDateTime time.Time `json:"lastChangeDateTime"`

	CFDocumentURI LinkUriType `json:"CFDocumentURI,omitempty"`
}
