/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ImsxCodeMinorFieldType - This is the container for a single code minor status code. 
type ImsxCodeMinorFieldType struct {

	// Model Primitive Datatype = NormalizedString
	ImsxCodeMinorFieldName string `json:"imsx_codeMinorFieldName"`

	ImsxCodeMinorFieldValue string `json:"imsx_codeMinorFieldValue"`
}
