/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

// CfItemType - This is the container for the CFItem data outside of the context of a CFPackage. This is the content that either describes a specific competency (learning objective) or describes a grouping of competencies within the taxonomy of a Competency Framework Document.
type CfItemType struct {

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	Identifier string `json:"identifier"`

	// Model Primitive Datatype = NormalizedString
	FullStatement string `json:"fullStatement"`

	// Model Primitive Datatype = NormalizedString
	AlternativeLabel string `json:"alternativeLabel,omitempty"`

	// Model Primitive Datatype = NormalizedString
	CFItemType string `json:"CFItemType,omitempty"`

	// Model Primitive Datatype = AnyURI
	Uri string `json:"uri"`

	// Model Primitive Datatype = NormalizedString
	HumanCodingScheme string `json:"humanCodingScheme,omitempty"`

	// Model Primitive Datatype = NormalizedString
	ListEnumeration string `json:"listEnumeration,omitempty"`

	// Model Primitive Datatype = NormalizedString
	AbbreviatedStatement string `json:"abbreviatedStatement,omitempty"`

	// Model Primitive Datatype = NormalizedString
	ConceptKeywords []string `json:"conceptKeywords,omitempty"`

	ConceptKeywordsURI LinkUriType `json:"conceptKeywordsURI,omitempty"`

	// Model Primitive Datatype = String
	Notes string `json:"notes,omitempty"`

	// Model Primitive Datatype = Language
	Language string `json:"language,omitempty"`

	// Model Primitive Datatype = NormalizedString
	EducationLevel []string `json:"educationLevel,omitempty"`

	CFItemTypeURI LinkUriType `json:"CFItemTypeURI,omitempty"`

	LicenseURI LinkUriType `json:"licenseURI,omitempty"`

	// Model Primitive Datatype = Date
	StatusStartDate string `json:"statusStartDate,omitempty"`

	// Model Primitive Datatype = Date
	StatusEndDate string `json:"statusEndDate,omitempty"`

	// Model Primitive Datatype = DateTime
	LastChangeDateTime time.Time `json:"lastChangeDateTime"`

	CFDocumentURI LinkUriType `json:"CFDocumentURI"`
}
