/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

// CfDocumentType - The container for the data about a competency framework document (CFDocument) when exchanged outside of the context of a CFPackage. A CFDocument is the root for the creation of a learning standard/competency.
type CfDocumentType struct {

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	Identifier string `json:"identifier"`

	// Model Primitive Datatype = AnyURI
	Uri string `json:"uri"`

	// Model Primitive Datatype = NormalizedString
	Creator string `json:"creator"`

	// Model Primitive Datatype = NormalizedString
	Title string `json:"title"`

	// Model Primitive Datatype = DateTime
	LastChangeDateTime time.Time `json:"lastChangeDateTime"`

	// The data-type for establishing a Uniform Resource Locator (URL) as defined by W3C.
	OfficialSourceURL string `json:"officialSourceURL,omitempty"`

	// Model Primitive Datatype = NormalizedString
	Publisher string `json:"publisher,omitempty"`

	// Model Primitive Datatype = NormalizedString
	Description string `json:"description,omitempty"`

	// Model Primitive Datatype = NormalizedString
	Subject []string `json:"subject,omitempty"`

	SubjectURI []LinkUriType `json:"subjectURI,omitempty"`

	// Model Primitive Datatype = Language
	Language string `json:"language,omitempty"`

	// Model Primitive Datatype = NormalizedString
	Version string `json:"version,omitempty"`

	// Model Primitive Datatype = NormalizedString
	AdoptionStatus string `json:"adoptionStatus,omitempty"`

	// Model Primitive Datatype = Date
	StatusStartDate string `json:"statusStartDate,omitempty"`

	// Model Primitive Datatype = Date
	StatusEndDate string `json:"statusEndDate,omitempty"`

	LicenseURI LinkUriType `json:"licenseURI,omitempty"`

	// Model Primitive Datatype = String
	Notes string `json:"notes,omitempty"`

	CFPackageURI LinkUriType `json:"CFPackageURI"`
}
