/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/ims/case/v1p0/",
		Index,
	},

	{
		"GetCFAssociation",
		http.MethodGet,
		"/ims/case/v1p0/CFAssociations/:sourcedId",
		GetCFAssociation,
	},

	{
		"GetCFItemAssociations",
		http.MethodGet,
		"/ims/case/v1p0/CFItemAssociations/:sourcedId",
		GetCFItemAssociations,
	},

	{
		"GetCFAssociationGrouping",
		http.MethodGet,
		"/ims/case/v1p0/CFAssociationGroupings/:sourcedId",
		GetCFAssociationGrouping,
	},

	{
		"GetCFConcept",
		http.MethodGet,
		"/ims/case/v1p0/CFConcepts/:sourcedId",
		GetCFConcept,
	},

	{
		"GetCFItemType",
		http.MethodGet,
		"/ims/case/v1p0/CFItemTypes/:sourcedId",
		GetCFItemType,
	},

	{
		"GetCFLicense",
		http.MethodGet,
		"/ims/case/v1p0/CFLicenses/:sourcedId",
		GetCFLicense,
	},

	{
		"GetCFSubject",
		http.MethodGet,
		"/ims/case/v1p0/CFSubjects/:sourcedId",
		GetCFSubject,
	},

	{
		"GetAllCFDocuments",
		http.MethodGet,
		"/ims/case/v1p0/CFDocuments",
		GetAllCFDocuments,
	},

	{
		"GetCFDocument",
		http.MethodGet,
		"/ims/case/v1p0/CFDocuments/:sourcedId",
		GetCFDocument,
	},

	{
		"GetCFItem",
		http.MethodGet,
		"/ims/case/v1p0/CFItems/:sourcedId",
		GetCFItem,
	},

	{
		"GetCFPackage",
		http.MethodGet,
		"/ims/case/v1p0/CFPackages/:sourcedId",
		GetCFPackage,
	},

	{
		"GetCFRubric",
		http.MethodGet,
		"/ims/case/v1p0/CFRubrics/:sourcedId",
		GetCFRubric,
	},
}
