/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// CfDefinitionType - The container for the set of definitions used for the competency framework i.e. the set of CFSubjects, CFConcepts, CFItemTypes, CFAssociationGroupings and CFLicenses.
type CfDefinitionType struct {
	CFConcepts []CfConceptType `json:"CFConcepts,omitempty"`

	CFSubjects []CfSubjectType `json:"CFSubjects,omitempty"`

	CFLicenses []CfLicenseType `json:"CFLicenses,omitempty"`

	CFItemTypes []CfItemTypeType `json:"CFItemTypes,omitempty"`

	CFAssociationGroupings []CfAssociationGroupingType `json:"CFAssociationGroupings,omitempty"`
}
