/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

// CfRubricCriterionLevelType - The container for the definition of a criterion level which is addressed by the competency framework.
type CfRubricCriterionLevelType struct {

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	Identifier string `json:"identifier"`

	// Model Primitive Datatype = AnyURI
	Uri string `json:"uri"`

	// Model Primitive Datatype = String
	Description string `json:"description,omitempty"`

	// Model Primitive Datatype = NormalizedString
	Quality string `json:"quality,omitempty"`

	// Model Primitive Datatype = Float
	Score float32 `json:"score,omitempty"`

	// Model Primitive Datatype = String
	Feedback string `json:"feedback,omitempty"`

	// Model Primitive Datatype = Integer
	Position int32 `json:"position,omitempty"`

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	RubricCriterionId string `json:"rubricCriterionId,omitempty"`

	// Model Primitive Datatype = DateTime
	LastChangeDateTime time.Time `json:"lastChangeDateTime"`
}
