/*
 * Competencies and Academic Standards Exchange (CASE) Service OpenAPI (YAML) Definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

// CfRubricCriterionType - The container for the definition of a rubric criterion which is addressed by the competency framework.
type CfRubricCriterionType struct {

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	Identifier string `json:"identifier"`

	// Model Primitive Datatype = AnyURI
	Uri string `json:"uri"`

	// Model Primitive Datatype = NormalizedString
	Category string `json:"category,omitempty"`

	// Model Primitive Datatype = String
	Description string `json:"description,omitempty"`

	CFItemURI LinkUriType `json:"CFItemURI,omitempty"`

	// Model Primitive Datatype = Float
	Weight float32 `json:"weight,omitempty"`

	// Model Primitive Datatype = Integer
	Position int32 `json:"position,omitempty"`

	// The data-type for establishing a Globally Unique Identifier (GUID). The form of the GUID is a Universally Unique Identifier (UUID) of 16 hexadecimal characters (lower case) in the format 8-4-4-4-12. All permitted versions (1-5) and variants (1-2) are supported.
	RubricId string `json:"rubricId,omitempty"`

	// Model Primitive Datatype = DateTime
	LastChangeDateTime time.Time `json:"lastChangeDateTime"`

	CFRubricCriterionLevels []CfRubricCriterionLevelType `json:"CFRubricCriterionLevels,omitempty"`
}
